import React, { useState, useEffect } from 'react';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container grid grid-cols-3 mx-auto">
          <div className="col-span-3 text-center mt-10">
            <h1 className="text-5xl p-3 font-bold ">Welcome To...The Word For You.</h1>
            <p className="text-md p-3">A Word For You is an interactive experience that uses AI to help connect your real-life experiences with scripture and the word from God..</p>
          </div>
        </div>
      </main>
    </>
  )
}
